### PR TITLE
If scale is too far out, set it to the next available

### PR DESCRIPTION
**Pull request by DeviateFromThePlan**
Brandon28AU's request in Discord.

### CODE REVIEW

**Comment by DeviateFromThePlan** [comment]
Hasn't been bug tested, can you guys please do so

**Comment by DeviateFromThePlan** [comment]
Looking good! I can't test (I'm on holidays) but it looks fine from my end.

**Review by 93ben — APPROVED** [review]
All good to go!

**Comment by DeviateFromThePlan** [comment]
No bugs and small enough so I'm just gonna merge

**Pull request merged**
